INSERT INTO WORD(WORD_ID, KO_WORD, WORD_TRANSLATION, FIRST_SENTENCE, SECOND_SENTENCE, THIRD_SENTENCE) VALUES('1', '여자','woman', '한 여자를 봤어 ','여자로 모르겠어','예쁜 여자인데다가 넌 키도 커요');

INSERT INTO WORD(WORD_ID, KO_WORD, WORD_TRANSLATION, FIRST_SENTENCE, SECOND_SENTENCE, THIRD_SENTENCE) VALUES('2', '남자','man','남자이에요' '남자이면 좋겠다','남자이서 너무 힘들어',);



